### ISSUE TITLE
Incorrect Health Checking config

### ISSUE THREAD

**Issue by mshaverdo** [turbinelabs/learnenvoy#71]
On https://www.learnenvoy.io/articles/health-check.html
following config is incorrect:
```
health_checks:
  - timeout: 1s
    interval: 60s
    interval_jitter: 1s
    unhealthy_threshold: 3
    healthy_threshold: 3
    tcp_health_check:
      send: ""
      receive: []
```
it causes parse error `INVALID_ARGUMENT:static_resources.clusters[1].health_checks[0].tcp_health_check.send: invalid value "" for type type.googleapis.com/envoy.api.v2.core.HealthCheck.Payload)`

It's better to replace 
```
    tcp_health_check:
      send: ""
      receive: []
```
with
`tcp_health_check: {}`
